name: android_logcat
description: A cross-platform desktop application for viewing and analyzing Android device logs in real-time.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.0
  process_run: ^1.0.0
  window_manager: ^0.3.0
  url_launcher: ^6.2.0
  file_picker: ^8.1.2
  flutter_querybuilder:
    git:
      url: https://github.com/exotic308/flutter-querybuilder.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
